"""
report.py
=========
One-page branded PDF brief generator for AgriTrue (pure-Python via fpdf2).

Charts are drawn natively with fpdf primitives (rectangles/text) rather than rendered
images, so the report generates anywhere with no headless-browser or image dependency.

Public functions return PDF bytes, ready for Streamlit's st.download_button.
"""

from __future__ import annotations

from typing import Optional

from fpdf import FPDF

# UNEP-ish palette (R,G,B)
GREEN = (42, 157, 143)
DARK = (38, 70, 83)
RED = (209, 73, 91)
SAND = (233, 196, 106)
GREY = (110, 110, 110)


class _Brief(FPDF):
    def header(self):
        self.set_fill_color(*DARK)
        self.rect(0, 0, 210, 22, "F")
        self.set_xy(10, 6)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 6, "AgriTrue  -  True Cost Accounting Brief")
        self.set_xy(10, 13)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 5, "TEEBAgriFood framework  -  calibrated to FAO SOFA 2024")
        self.ln(16)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*GREY)
        self.multi_cell(
            0, 3.5,
            "Generated by AgriTrue. Figures use Poore & Nemecek (2018) LCA medians and a "
            "social cost of carbon (Rennert et al. 2022). Values are estimates shown with "
            "uncertainty; per-country splits are modelled to match SOFA 2024 aggregates.",
            align="C")


_UNICODE_MAP = {
    "—": "-", "–": "-", "−": "-", "‑": "-",  # dashes / minus
    "≈": "~", "·": "-", "…": "...", "×": "x",
    "‘": "'", "’": "'", "“": '"', "”": '"',
    "₹": "INR ", "€": "EUR ", " ": " ",
}


def _san(text: str) -> str:
    """Make text safe for the latin-1 core PDF font (the briefs use no embedded Unicode font)."""
    text = str(text).replace("**", "")
    for u, a in _UNICODE_MAP.items():
        text = text.replace(u, a)
    return text.encode("latin-1", "replace").decode("latin-1")


def _section(pdf: FPDF, title: str):
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*DARK)
    pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(*GREEN)
    pdf.set_line_width(0.6)
    y = pdf.get_y()
    pdf.line(10, y, 200, y)
    pdf.ln(2)
    pdf.set_text_color(0, 0, 0)


def _kpi_row(pdf: FPDF, kpis: list[tuple[str, str]]):
    """Render up to 4 KPI cards in a row."""
    n = len(kpis)
    w = 190 / n
    x0 = 10
    y0 = pdf.get_y()
    for i, (label, value) in enumerate(kpis):
        x = x0 + i * w
        pdf.set_fill_color(245, 247, 246)
        pdf.rect(x, y0, w - 3, 18, "F")
        pdf.set_xy(x + 2, y0 + 2)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*GREY)
        pdf.multi_cell(w - 6, 3.4, label.upper())
        pdf.set_xy(x + 2, y0 + 9)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(*DARK)
        pdf.cell(w - 6, 7, value)
    pdf.set_xy(x0, y0 + 22)
    pdf.set_text_color(0, 0, 0)


def _hbar_chart(pdf: FPDF, rows: list[tuple[str, float]], unit: str, color=GREEN):
    """Draw a horizontal bar chart from (label, value) rows."""
    if not rows:
        return
    max_v = max(abs(v) for _, v in rows) or 1.0
    bar_x = 60
    bar_w_max = 130
    row_h = 7
    pdf.set_font("Helvetica", "", 8.5)
    for label, val in rows:
        y = pdf.get_y()
        pdf.set_text_color(0, 0, 0)
        pdf.set_xy(10, y)
        pdf.cell(48, row_h, label[:30])
        w = bar_w_max * (abs(val) / max_v)
        pdf.set_fill_color(*(RED if val < 0 else color))
        pdf.rect(bar_x, y + 1.2, max(w, 0.4), row_h - 2.4, "F")
        pdf.set_xy(bar_x + w + 2, y)
        pdf.set_text_color(*GREY)
        pdf.cell(30, row_h, f"{val:,.2f} {unit}")
        pdf.ln(row_h)
    pdf.set_text_color(0, 0, 0)


def _new() -> _Brief:
    pdf = _Brief()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    return pdf


# ---------------------------------------------------------------------------
# Public builders
# ---------------------------------------------------------------------------
def true_price_pdf(result: dict) -> bytes:
    """One-pager for a single True Price Calculator result."""
    pdf = _new()
    _section(pdf, f"True price of {result['commodity']}  ({result['mass_kg']:g} kg)")
    hc = result["hidden_cost"]
    _kpi_row(pdf, [
        ("Market price", f"${result['market_price']:.2f}"),
        ("Hidden cost", f"${hc['central']:.2f}"),
        ("True price", f"${result['true_price']:.2f}"),
        ("Hidden : market", f"{result['hidden_to_market_ratio']:.2f}x"),
    ])
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5,
        f"Hidden-cost uncertainty band: ${hc['low']:.2f} - ${hc['high']:.2f}. "
        f"The market price omits the environmental externalities below, which society "
        f"pays through climate damage, water stress, nutrient pollution and land conversion.")
    pdf.ln(2)
    _section(pdf, "Hidden cost by externality")
    rows = [(k.title(), v["central"]) for k, v in result["components"].items()]
    rows.sort(key=lambda r: r[1], reverse=True)
    _hbar_chart(pdf, rows, "USD")
    return bytes(pdf.output())


def diet_pdf(comparison: dict) -> bytes:
    """One-pager comparing a diet pattern against the EAT-Lancet reference."""
    pdf = _new()
    a, b = comparison["diet_a"], comparison["diet_b"]
    ra, rb = comparison["result_a"], comparison["result_b"]
    _section(pdf, f"Diet true-cost comparison")
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5, f"{a}  vs  {b}  (annual hidden cost per person)")
    pdf.ln(1)
    _kpi_row(pdf, [
        (f"{a[:18]} hidden cost", f"${ra['total_hidden_cost_usd_yr']:,.0f}/yr"),
        (f"{b[:18]} hidden cost", f"${rb['total_hidden_cost_usd_yr']:,.0f}/yr"),
        ("Difference", f"${comparison['delta_usd_yr']:,.0f}/yr"),
        ("vs reference", f"{comparison['delta_pct']:+.0f}%"),
    ])
    _section(pdf, "Footprint difference (A - reference)")
    _hbar_chart(pdf, [
        ("GHG (kg CO2e/yr)", comparison["ghg_delta_kg_yr"]),
        ("Hidden cost (USD/yr)", comparison["delta_usd_yr"]),
    ], "", color=DARK)
    _section(pdf, f"Top cost contributors - {a}")
    rows = [(f["commodity"], f["hidden_cost_usd_yr"]) for f in ra["foods"][:8]]
    _hbar_chart(pdf, rows, "USD/yr")
    return bytes(pdf.output())


def teeb_study_pdf(study: dict, comparison: dict) -> bytes:
    """One-pager for a localized TEEBAgriFood scenario comparison (B vs A)."""
    pdf = _new()
    a, b = comparison["scenario_a"], comparison["scenario_b"]
    _section(pdf, _san(study["name"]))
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5, _san(
        f"{study['country']}  -  {b} vs {a}.  Basis: {study['basis']}.\n{study['summary']}"))
    pdf.ln(1)
    def _m(v):  # keep decimals for small (e.g. Billion-USD) magnitudes; integers for large
        return f"${v:,.2f}" if abs(v) < 100 else f"${v:,.0f}"
    _kpi_row(pdf, [
        ("Net societal value change", _m(comparison['delta_net_societal'])),
        ("Farmer's private change", _m(comparison['delta_private'])),
        ("External (society) change", _m(comparison['delta_external'])),
        ("Basis", _san(study["basis"].split("(")[0][:18])),
    ])
    _section(pdf, _san(f"Change in capital flows ({b} - {a})"))
    from tca.teeb_studies import CAPITAL_LABELS
    _hbar_chart(pdf, [
        (_san(CAPITAL_LABELS[c]), comparison["delta_by_capital"][c])
        for c in ("produced", "natural", "human", "social")
    ], "", color=DARK)
    pdf.ln(1)
    pdf.set_font("Helvetica", "I", 7.5)
    pdf.set_text_color(*GREY)
    pdf.multi_cell(0, 3.5, _san(
        f"Source: {study['source']}  Values are taken from the cited report (or derived from its "
        f"published figures) and are adjustable in the app for sensitivity analysis."))
    pdf.set_text_color(0, 0, 0)
    return bytes(pdf.output())


def national_pdf(country: dict, global_anchors: dict) -> bytes:
    """One-pager for a country's hidden-cost profile."""
    pdf = _new()
    _section(pdf, f"National hidden-cost profile - {country['name']}")
    _kpi_row(pdf, [
        ("Total hidden cost", f"${country['hidden_total_busd']:,.0f}bn/yr"),
        ("Share of GDP", f"{country['hc_pct_gdp']*100:.1f}%"),
        ("Agrifood system", country["system"]),
        ("Region", country["region"]),
    ])
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5,
        f"Global context: agrifood systems carry ~${global_anchors['total_hidden_cost_trillion_usd']:.0f} "
        f"trillion/yr in hidden costs (~{global_anchors['share_of_global_gdp']*100:.0f}% of global GDP), "
        f"~{global_anchors['health_share']*100:.0f}% health-driven (FAO SOFA 2024).")
    pdf.ln(1)
    _section(pdf, "Hidden cost by capital (USD bn / yr)")
    _hbar_chart(pdf, [
        ("Health", country["health_busd"]),
        ("Environmental", country["env_busd"]),
        ("Social", country["social_busd"]),
    ], "bn")
    return bytes(pdf.output())
